### ISSUE TITLE
No matched printer: LABEL

### ISSUE THREAD

**Issue by drors01** [imTigger/webapp-hardware-bridge#14]
Hello

Thanks for this bridge!.

I am not sure what I do wrong or if I have something not set up rigth,
The LAEL is mapped to and actual printer I have on my network.

This is the log:

01:54:23.906 [Dror][WebSocketWorker-27] INFO  tigerworkshop.webapphardwarebridge.utils.DownloadUtil.file() @18 - Downloading file from: https://tcpdf.org/files/examples/example_002.pdf
01:54:24.361 [Dror][WebSocketWorker-27] INFO  tigerworkshop.webapphardwarebridge.utils.DownloadUtil.file() @59 - File documents/example_002.pdf downloaded in 455ms
01:54:24.362 [Dror][WebSocketWorker-27] DEBUG tigerworkshop.webapphardwarebridge.websocketservices.PrinterWebSocketService.printPDF() @198 - printPDF::PrintDocument{type='LABEL', url='https://tcpdf.org/files/examples/example_002.pdf', id='null', qty=1, file_content='null', raw_content='null', extras=[]}
01:54:24.362 [Dror][WebSocketWorker-27] ERROR tigerworkshop.webapphardwarebridge.websocketservices.PrinterWebSocketService.printDocument() @87 - Document Print Error, deleting downloaded document
01:54:24.363 [Dror][WebSocketWorker-27] ERROR tigerworkshop.webapphardwarebridge.websocketservices.PrinterWebSocketService.onDataReceived() @56 - java.awt.print.PrinterException
01:54:24.363 [Dror][WebSocketWorker-27] DEBUG tigerworkshop.webapphardwarebridge.websocketservices.PrinterWebSocketService.onDataReceived() @57 - No matched printer: LABEL
java.awt.print.PrinterException: No matched printer: LABEL
	at tigerworkshop.webapphardwarebridge.websocketservices.PrinterWebSocketService.getDocPrintJob(PrinterWebSocketService.java:288) ~[webapp-hardware-bridge.jar:?]
	at tigerworkshop.webapphardwarebridge.websocketservices.PrinterWebSocketService.printPDF(PrinterWebSocketService.java:204) ~[webapp-hardware-bridge.jar:?]
	at tigerworkshop.webapphardwarebridge.websocketservices.PrinterWebSocketService.printDocument(PrinterWebSocketService.java:80) ~[webapp-hardware-bridge.jar:?]
	at tigerworkshop.webapphardwarebridge.websocketservices.PrinterWebSocketService.onDataReceived(PrinterWebSocketService.java:54) [webapp-hardware-bridge.jar:?]
	at tigerworkshop.webapphardwarebridge.BridgeWebSocketServer.processMessage(BridgeWebSocketServer.java:159) [webapp-hardware-bridge.jar:?]
	at tigerworkshop.webapphardwarebridge.BridgeWebSocketServer.onMessage(BridgeWebSocketServer.java:83) [webapp-hardware-bridge.jar:?]
	at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:642) [Java-WebSocket-1.4.0.jar:?]
	at org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:858) [Java-WebSocket-1.4.0.jar:?]
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:792) [Java-WebSocket-1.4.0.jar:?]
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:381) [Java-WebSocket-1.4.0.jar:?]
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:218) [Java-WebSocket-1.4.0.jar:?]
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1011) [Java-WebSocket-1.4.0.jar:?]
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:993) [Java-WebSocket-1.4.0.jar:?]

**Comment by drors01** [comment]
And can I print an html webpage?

**Comment by drors01** [comment]
Uninstall and re-install solved the problem.
I managed to print from the example. 

I also use the html2canvas but not successfull in combining both to work.

Is there an example of PNG print?
