### ISSUE TITLE
RAW Print Don't Work

### ISSUE THREAD

**Issue by glaydsongmv** [imTigger/webapp-hardware-bridge#22]
I'm testing with the examples, but RAW print don't work. The tests with PDF print examples works fine. I get this error in the app log:

`18:58:30.555 [DESKTOP-U02HD0U][WebSocketWorker-30] DEBUG tigerworkshop.webapphardwarebridge.websocketservices.PrinterWebSocketService.printRaw() @135 - printRaw::PrintDocument{type='RECEIPT', url='null', id='null', qty=1, file_content='null', raw_content='G0AbQBthAEhlbGxvIFdvcmxkCh0hERthAUVTQy9QT1MgUHJpbnRlciBUZXN0Ch0hABthAkdvb2RieWUgV29ybGQKHVZBAw==', extras=[]}
18:58:30.555 [DESKTOP-U02HD0U][WebSocketWorker-30] ERROR tigerworkshop.webapphardwarebridge.websocketservices.PrinterWebSocketService.printDocument() @87 - Document Print Error, deleting downloaded document
18:58:30.555 [DESKTOP-U02HD0U][WebSocketWorker-30] ERROR tigerworkshop.webapphardwarebridge.websocketservices.PrinterWebSocketService.onDataReceived() @56 - java.lang.NullPointerException
18:58:30.556 [DESKTOP-U02HD0U][WebSocketWorker-30] DEBUG tigerworkshop.webapphardwarebridge.websocketservices.PrinterWebSocketService.onDataReceived() @57 - null
java.lang.NullPointerException: null
	at tigerworkshop.webapphardwarebridge.services.DocumentService.getPathFromUrl(DocumentService.java:49) ~[webapp-hardware-bridge.jar:?]
	at tigerworkshop.webapphardwarebridge.services.DocumentService.getFileFromUrl(DocumentService.java:41) ~[webapp-hardware-bridge.jar:?]
	at tigerworkshop.webapphardwarebridge.services.DocumentService.deleteFileFromUrl(DocumentService.java:45) ~[webapp-hardware-bridge.jar:?]
	at tigerworkshop.webapphardwarebridge.websocketservices.PrinterWebSocketService.printDocument(PrinterWebSocketService.java:88) ~[webapp-hardware-bridge.jar:?]
	at tigerworkshop.webapphardwarebridge.websocketservices.PrinterWebSocketService.onDataReceived(PrinterWebSocketService.java:54) [webapp-hardware-bridge.jar:?]
	at tigerworkshop.webapphardwarebridge.BridgeWebSocketServer.processMessage(BridgeWebSocketServer.java:159) [webapp-hardware-bridge.jar:?]
	at tigerworkshop.webapphardwarebridge.BridgeWebSocketServer.onMessage(BridgeWebSocketServer.java:83) [webapp-hardware-bridge.jar:?]
	at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:642) [Java-WebSocket-1.4.0.jar:?]
	at org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:858) [Java-WebSocket-1.4.0.jar:?]
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:792) [Java-WebSocket-1.4.0.jar:?]
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:381) [Java-WebSocket-1.4.0.jar:?]
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:218) [Java-WebSocket-1.4.0.jar:?]
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1011) [Java-WebSocket-1.4.0.jar:?]
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:993) [Java-WebSocket-1.4.0.jar:?]
`
I'm using v0.10.0 in Windows 10 64-bit. Thank's.

**Comment by FractalMind** [comment]
DEMO: **printer-basic.htm**

PDF by URL: **working**
PDF by Base64: **working**
Raw (ESC/POS): **error**

`java -cp webapp-hardware-bridge.jar tigerworkshop.webapphardwarebridge.Server
19:28:18.073 INFO  Application Started
19:28:18.077 INFO  Program Version: 0.13.0
19:28:18.118 INFO  Starting SerialWebSocketService on COM5
19:28:18.125 INFO  Starting PrinterWebSocketService
19:28:18.125 INFO  WebSocket started on ws://127.0.0.1:12212
19:28:18.137 INFO  BridgeWebSocketServer started
19:28:18.923 INFO  /127.0.0.1:58296 connected to /printer
19:28:19.490 INFO  /127.0.0.1:58298 connected to /printer
19:28:39.146 ERROR Document Print Error, deleting downloaded document
19:28:39.146 ERROR java.lang.NullPointerException
`
Any hint to fix it?

**Comment by FractalMind** [comment]
Answer here
 https://github.com/imTigger/webapp-hardware-bridge/issues/31
